baseurl = "https://savethedigitalnomad.github.io"
metaDataFormat = "yaml"
title = "Save The Digital Nomad"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Saverio"
      introSubtitle = "Software engineer who enjoys social card games, blogging and painting"
      introPhoto = "/profile.jpeg"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4
        
  #[languages.it]
  # contentDir = "content/it" #Italian
  # weight = 1
  # languageName = "Italiano"
  # [languages.it.params]
  #   introTitle = "Ciao! Sono Saverio Veltri"
  #   introSubtitle = "Software engineer who enjoys social card games, blogging and painting"
  #   introPhoto = "/profile.jpeg"
  #   logo = "/blist-logo.png"
  # [[languages.it.menu.main]]
  #     name = "Blog"
  #     url = "blog"
  #     weight = 1

  # [[languages.it.menu.main]]
  #     name = "A proposito"
  #     url = "page/about/"
  #     weight = 2

  # [[languages.it.menu.main]]
  #     name = "Tags"
  #     url = "tags"
  #     weight = 3
        
[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Saverio Veltri · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color itom TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the itont page
  itontBundle = "blog"

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = ""
  twitter = "https://twitter.com/save_veltri"
  linkedin = "https://linkedin.com/in/saveveltri"
  github = "https://github.com/save_veltri"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
